// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBlF3f3XmDAq3s5iBhMwV-k1et55Om6I0',
    appId: '1:473187258795:web:76de1a76a649d9a86542ee',
    messagingSenderId: '473187258795',
    projectId: 'appdessert',
    authDomain: 'appdessert.firebaseapp.com',
    storageBucket: 'appdessert.firebasestorage.app',
    measurementId: 'G-KQQT9SL0BF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxk-B5NjS6K54Jl5VQVAtSj0Wgg92ksec',
    appId: '1:473187258795:android:3fc6d87a93e002d66542ee',
    messagingSenderId: '473187258795',
    projectId: 'appdessert',
    storageBucket: 'appdessert.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoxDNNYQcwmpVtQgUAV2jzGmMIXnVjrKw',
    appId: '1:473187258795:ios:8c9173df58f345556542ee',
    messagingSenderId: '473187258795',
    projectId: 'appdessert',
    storageBucket: 'appdessert.firebasestorage.app',
    androidClientId: '473187258795-ib3199tthp2ptq661kq3h5bo38b3ssu3.apps.googleusercontent.com',
    iosClientId: '473187258795-sh24k9dfk8acncc2gh66jngkp8n538iv.apps.googleusercontent.com',
    iosBundleId: 'com.example.appTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoxDNNYQcwmpVtQgUAV2jzGmMIXnVjrKw',
    appId: '1:473187258795:ios:8c9173df58f345556542ee',
    messagingSenderId: '473187258795',
    projectId: 'appdessert',
    storageBucket: 'appdessert.firebasestorage.app',
    androidClientId: '473187258795-ib3199tthp2ptq661kq3h5bo38b3ssu3.apps.googleusercontent.com',
    iosClientId: '473187258795-sh24k9dfk8acncc2gh66jngkp8n538iv.apps.googleusercontent.com',
    iosBundleId: 'com.example.appTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBlF3f3XmDAq3s5iBhMwV-k1et55Om6I0',
    appId: '1:473187258795:web:a4b23773038f0b306542ee',
    messagingSenderId: '473187258795',
    projectId: 'appdessert',
    authDomain: 'appdessert.firebaseapp.com',
    storageBucket: 'appdessert.firebasestorage.app',
    measurementId: 'G-GNLTXXK76E',
  );
}
